apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
